index:
   path: /
   controller: App\Controller\DefaultController::index
   methods: GET

api_root:
    path: /api
    controller: App\Controller\DefaultController::index
    methods: GET

api_invoices:
    path:       /api/invoices/report
    controller: App\Controller\InvoicesReportController::index
    methods:    GET